#!/bin/sh
set -eu

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS linkforge CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${MYSQL_API_USER}'@'%' IDENTIFIED BY '${MYSQL_API_PASSWORD}';
GRANT ALL PRIVILEGES ON linkforge.* TO '${MYSQL_API_USER}'@'%';

CREATE USER IF NOT EXISTS '${MYSQL_READ_USER}'@'%' IDENTIFIED BY '${MYSQL_READ_PASSWORD}';
GRANT SELECT ON linkforge.* TO '${MYSQL_READ_USER}'@'%';

CREATE USER IF NOT EXISTS '${MYSQL_REPLICATION_USER}'@'%' IDENTIFIED BY '${MYSQL_REPLICATION_PASSWORD}';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO '${MYSQL_REPLICATION_USER}'@'%';

FLUSH PRIVILEGES;
SQL
